[package]
name = "bot-man"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
log = "0.4.25"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.13", features = ["macros"] }
teloxide_tests = "0.2.0"
tokio = { version = "1.43.0", features = ["full"] }
